# mongodb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment # Un nombre más descriptivo para el deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest # Asegúrate de que esta sea la imagen que tienes (ya la tienes, según image_67b3f3.png)
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password # ¡IMPORTANTE! Cambia esto por una contraseña segura en un entorno real o usa Secrets de Kubernetes.
        # Opcional: Si quieres persistencia de datos, añade un volumeMount y un PersistentVolumeClaim.
        # volumeMounts:
        # - name: mongodb-persistent-storage
        #   mountPath: /data/db
        # volumes:
        # - name: mongodb-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mongodb-pvc # Tendrías que definir este PersistentVolumeClaim por separado.
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # Un servicio dedicado que apuntará a tu Deployment
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP